"use strict";

let phrases = [
  "You got this!",
  "You're awesome!",
  "Nice work!",
  "Excellent job on that project.",
  "Thanks for helping out.",
  "Wow, that's impressive work.",
  "Congratulations on a job well done.",
  "Outstanding work!",
  "You are a fast learner.",
  "You're so good at what you do.",
  "I don't know what we would do without you.",
  "I'm so proud of your effort.",
  "You truly make a difference here.",
  "Your work is incredible.",
  "Your work is going to leave a lasting impression on our clients.",
  "This is great. Can I share your work with our top executives?",
  "Your progress is truly inspiring.",
  "I really like this.",
  "How did you do this so fast?",
  "Good idea. I wouldn't have thought of it that way!",
  "You need to show our manager this.",
  "You have really grown as a professional.",
  "Terrific job!",
  "Now this is good work.",
  "Can I add this to our training materials?",
  "Are you willing to present this to our team?",
  "You're doing this right.",
  "I'm so thankful to have you on my team.",
  "You are such a wonderful person to work with every day.",
  "I really enjoyed looking through your work.",
  "I'm excited to see what you will do next.",
  "Your contributions are noticed.",
  "Thank you for inspiring me with your amazing work.",
  "I'm grateful to call you my colleague.",
  "You are essential to our team.",
  "How did you think of this? Incredible!",
  "I would love to learn more about your thought process on this.",
  "This proves you are ready for more here.",
  "Your effort makes me proud.",
  "I knew you had it in you.",
  "See, I knew you could do it!",
  "I never doubted you for a moment.",
  "Your level of expertise is impressive.",
  "Wow, you are so skilled!",
  "Look at those skills!",
  "This is insanely good.",
  "I can tell your practice was well worth it.",
  "You're going to go onto to great things.",
  "What an amazing success!",
  "This is what excellence looks like.",
  "I can tell this means a lot to you.",
  "Beautiful work.",
  "You were awesome today.",
  "This is what I like to see.",
  "If you do this every time, we are going to meet our goals.",
  "You deserve a raise!",
  "Your extra effort makes me so happy.",
  "This is delightful.",
  "It's clear that you pay attention to detail.",
  "Your work matters to me.",
  "Let's go with your idea.",
  "Interesting insight. Tell me more!",
  "Your work ethic is admirable.",
  "Our new hires see you as a role model.",
  "I hope to be as good as you one day.",
  "You handled that challenge like a true professional.",
  "Your perspective is essential to this project.",
  "You always deliver the best results.",
  "This is true craftsmanship.",
  "Fantastic!",
  "You're making a real difference in our field.",
  "Your standards make our team better.",
  "I'm using this as an example of a great project.",
  "You could lead this company one day.",
  "Your work is so thoughtful and well done.",
  "This may have been a lot, but you truly made the best of it.",
  "I can see you are passionate about your work.",
  "I envy your work ethic.",
  "This is why I love working with you.",
  "You're such a forward thinker.",
  "This is so innovative!",
  "Smart thinking. I'm glad I asked for your help.",
  "You always have the best input.",
  "Your opinions help our team so much.",
  "This is going to 'wow' our clients.",
  "I'm never going to forget this.",
  "You just keep getting better at this.",
];

let motivate = function () {
  let ran_num = Math.floor(Math.random() * phrases.length);
  document.querySelector("#phrase").innerHTML = phrases[ran_num];
};
